### ISSUE TITLE
Shutters

### ISSUE THREAD

**Issue by Rens93** [djangosoe/homebridge-ics1000-django#1]
Is it possible to add blinds? Like OpenClose ? 
I've add them as OnOff but it's not perfect..

**Comment by Rens93** [comment]
So, the only thing I have to do, is change OnOff in OpenClose ? 
Or when will this be functional?

**Comment by Rens93** [comment]
Could you please edit the code for open/close/percentage?
You would help me a lot!

**Comment by djangosoe** [comment]
I am going to work on the project this week, I have finally a roller shutter to test it with.

**Comment by Rens93** [comment]
Thank you very much for your time!

Unfortunately I get the next error;

/usr/local/lib/node_modules/homebridge/lib/api.js:64
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
            ^
Error: The requested accessory 'ICS1000-Window' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:286:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:87:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

**Comment by Rens93** [comment]
Open/Close is working great, only the % is not working.

**Comment by djangosoe** [comment]
Thanks for the npm install link.
The default position is closed, but this will only reset when homebridge is restarted.
What do you mean by % is not working, what are you values by open and close time?

**Comment by Rens93** [comment]
[2018-9-23 12:38:36] [Rolluik Woonkamer 44] calling setTargetPosition from:  100 to:  75
[2018-9-23 12:38:36] [Rolluik Woonkamer 44] SendOFF for:  0.25 seconds Room= 5 Device= 1 name= Rolluik Woonkamer 44
[2018-9-23 12:38:36] [Rolluik Woonkamer 44] SendOFF to stop moving Room= undefined Device= undefined name= undefined
